// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtxvbdvhzjsktmhdfdfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0eHZiZHZoempza3RtaGRmZGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzAwNzAsImV4cCI6MjA2NDYwNjA3MH0.JJpcbEVIvKmA2Z-nG231PF-R1O8NTh2zjEolm_vzxn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);